# Generated by Django 6.0 on 2025-12-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('height', models.FloatField(default=0.0, verbose_name='身高(cm)')),
                ('weight', models.FloatField(default=0.0, verbose_name='体重(kg)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='SportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('跑步', '跑步'), ('快走', '快走'), ('跳绳', '跳绳'), ('篮球', '篮球'), ('羽毛球', '羽毛球'), ('游泳', '游泳'), ('骑行', '骑行'), ('瑜伽', '瑜伽'), ('健身', '健身'), ('其他', '其他')], max_length=20, verbose_name='运动类型')),
                ('duration', models.IntegerField(verbose_name='运动时长(分钟)')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '运动记录',
                'verbose_name_plural': '运动记录',
                'db_table': 'sport_record',
            },
        ),
        migrations.CreateModel(
            name='HealthIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(choices=[('体重', '体重'), ('收缩压', '收缩压'), ('舒张压', '舒张压'), ('心率', '心率')], max_length=10, verbose_name='指标类型')),
                ('value', models.FloatField(verbose_name='指标数值')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '健康指标',
                'verbose_name_plural': '健康指标',
                'db_table': 'health_index',
            },
        ),
        migrations.CreateModel(
            name='DietRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50, verbose_name='食材名')),
                ('amount', models.IntegerField(verbose_name='食用量(克)')),
                ('meal_time', models.CharField(choices=[('早餐', '早餐'), ('午餐', '午餐'), ('晚餐', '晚餐'), ('加餐', '加餐')], max_length=10, verbose_name='用餐时段')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '饮食记录',
                'verbose_name_plural': '饮食记录',
                'db_table': 'diet_record',
            },
        ),
    ]
