# Generated by Django 6.0 on 2025-12-29 05:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('height', models.FloatField(default=0.0, verbose_name='身高(cm)')),
                ('weight', models.FloatField(default=0.0, verbose_name='体重(kg)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DietRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50, verbose_name='食材名')),
                ('amount', models.IntegerField(verbose_name='食用量(克)')),
                ('meal_time', models.CharField(choices=[('早餐', '早餐'), ('午餐', '午餐'), ('晚餐', '晚餐'), ('加餐', '加餐')], max_length=10, verbose_name='用餐时段')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '饮食记录',
                'verbose_name_plural': '饮食记录',
                'db_table': 'diet_record',
            },
        ),
        migrations.CreateModel(
            name='HealthIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_type', models.CharField(choices=[('体重', '体重'), ('收缩压', '收缩压'), ('舒张压', '舒张压'), ('心率', '心率')], max_length=10, verbose_name='指标类型')),
                ('value', models.FloatField(verbose_name='指标数值')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '健康指标',
                'verbose_name_plural': '健康指标',
                'db_table': 'health_index',
            },
        ),
        migrations.CreateModel(
            name='SportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('跑步', '跑步'), ('快走', '快走'), ('跳绳', '跳绳'), ('篮球', '篮球'), ('羽毛球', '羽毛球'), ('游泳', '游泳'), ('骑行', '骑行'), ('瑜伽', '瑜伽'), ('健身', '健身'), ('其他', '其他')], max_length=20, verbose_name='运动类型')),
                ('duration', models.IntegerField(verbose_name='运动时长(分钟)')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '运动记录',
                'verbose_name_plural': '运动记录',
                'db_table': 'sport_record',
            },
        ),
    ]
